version: '2'
services:
  xml-upload-service:
    container_name: xml-upload-service
    build:
      context: docker-xml-upload-service
      dockerfile: Dockerfile
    image: xml-upload-service-0.0.1:latest
    ports:
      - 8080:8080
