version: '2'
services:
  xml-upload-service:
    container_name: xml-upload-service
    build:
      context: docker-xml-upload-service
      dockerfile: Dockerfile
    image: xml-upload-service:latest
    ports:
      - 8080:8080
    networks:
      - my-task-network

networks:
  my-task-network:
    driver: bridge